# Generated by Django 3.1.7 on 2021-04-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='代码')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('increase', models.CharField(max_length=20, verbose_name='涨幅')),
                ('current_price', models.CharField(max_length=20, verbose_name='现价')),
                ('ups_and_downs', models.CharField(max_length=20, verbose_name='涨跌')),
                ('purchase_price', models.CharField(max_length=20, verbose_name='买价')),
                ('sell_price', models.CharField(max_length=20, verbose_name='卖价')),
                ('total_volume', models.CharField(max_length=20, verbose_name='总手')),
                ('total', models.CharField(max_length=20, verbose_name='总金额')),
                ('current_volume', models.CharField(max_length=20, verbose_name='现手')),
                ('rate_increase', models.CharField(max_length=20, verbose_name='涨速')),
                ('entity_increse', models.CharField(max_length=20, verbose_name='实体涨幅')),
                ('current_differences', models.CharField(max_length=20, verbose_name='现均差')),
                ('turnover', models.CharField(max_length=20, verbose_name='换手率')),
                ('committee', models.CharField(max_length=20, verbose_name='委比')),
                ('total_value', models.CharField(max_length=20, verbose_name='总市值')),
                ('circulation_value', models.CharField(max_length=20, verbose_name='流通市值')),
                ('circulation_rate', models.CharField(max_length=20, verbose_name='流通比例')),
                ('s', models.CharField(max_length=20, verbose_name='内盘')),
                ('b', models.CharField(max_length=20, verbose_name='外盘')),
                ('s_b', models.CharField(max_length=20, verbose_name='内外比')),
                ('remarks', models.CharField(max_length=20, verbose_name='备注')),
                ('bad_news', models.CharField(max_length=20, verbose_name='利空')),
                ('good_news', models.CharField(max_length=20, verbose_name='利好')),
                ('DDE', models.CharField(max_length=20, verbose_name='主力净量')),
                ('QRR', models.CharField(blank=True, max_length=20, null=True, verbose_name='量比')),
                ('TTM', models.CharField(max_length=20, verbose_name='市盈率')),
                ('NP', models.CharField(max_length=20, verbose_name='净利润')),
                ('MNR', models.CharField(max_length=20, verbose_name='市净率')),
                ('PP', models.CharField(max_length=20, verbose_name='每股盈利')),
                ('de_industry', models.CharField(max_length=20, verbose_name='细分行业')),
                ('industry', models.CharField(max_length=20, verbose_name='行业')),
                ('yincome', models.CharField(max_length=20, verbose_name='昨收')),
                ('opening_quotation', models.CharField(max_length=20, verbose_name='开盘')),
                ('oir', models.CharField(max_length=20, verbose_name='开盘涨幅')),
                ('hightest', models.CharField(max_length=20, verbose_name='最高')),
                ('lowest', models.CharField(max_length=20, verbose_name='最低')),
                ('fivedays', models.CharField(max_length=20, verbose_name='5日涨幅')),
                ('tendays', models.CharField(max_length=20, verbose_name='10日涨幅')),
                ('twentydays', models.CharField(max_length=20, verbose_name='20日涨幅')),
                ('form_now', models.CharField(max_length=20, verbose_name='年初至今')),
                ('amplitude', models.CharField(max_length=20, verbose_name='振幅')),
                ('BQ', models.CharField(max_length=20, verbose_name='买量')),
                ('SQ', models.CharField(max_length=20, verbose_name='卖量')),
                ('count', models.CharField(max_length=20, verbose_name='笔数')),
                ('contribution', models.CharField(blank=True, max_length=20, null=True, verbose_name='贡献度')),
                ('institutional_trends', models.CharField(max_length=20, verbose_name='机构动向')),
                ('type', models.CharField(max_length=20, verbose_name='异动类型')),
                ('general_capital', models.CharField(max_length=20, verbose_name='总股本')),
                ('circulation_capital', models.CharField(max_length=20, verbose_name='流通股本')),
                ('total_profit', models.CharField(max_length=20, verbose_name='总利润')),
                ('profit_rate', models.CharField(max_length=20, verbose_name='利润率')),
                ('PPS', models.CharField(max_length=20, verbose_name='每股净资产')),
                ('goleden_cross', models.CharField(max_length=20, verbose_name='金叉个数')),
                ('number_of_retail_investors', models.CharField(max_length=20, verbose_name='散户数量')),
            ],
        ),
    ]
