# Generated by Django 3.1.7 on 2021-04-23 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0003_auto_20210415_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mystock',
            options={'verbose_name': '我收藏的股票', 'verbose_name_plural': '我收藏的股票'},
        ),
        migrations.AlterField(
            model_name='mystock',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='收藏时间'),
        ),
        migrations.CreateModel(
            name='Condition_Sheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stock', verbose_name='我的股票')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
        migrations.AddField(
            model_name='mystock',
            name='conditions_sheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.condition_sheet', verbose_name='止盈止损条件单'),
        ),
    ]
